name: Lint with Ruff

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies (including Ruff)
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run Ruff linter
        run: |
          ruff check .  # Run Ruff on the current directory

      - name: Upload Ruff results to GitHub actions
        if: failure()
        run: |
          echo "Ruff linting failed."
